matrix:
    include:
        - name: "Linux pytest"
          services:
            - docker
          language: minimal
          env:
            - BUILD_WHEEL=true
            - OS=linux
        - name: "macOS py3.7"
          os: osx
          language: shell
          osx_image: xcode10.1
          env: OS=osx
          addons:
              homebrew:
                packages:
                - gcc@8
                - verilator


script:
    - ./scripts/ci.sh

deploy:
  - provider: script
    script: /bin/bash scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
      tags: true
